spring:
  application:
    name: coffee-machine-mqtt-worker
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  mqtt:
    broker:
      url: tcp://localhost:1883
      client-id: coffee-machine-mqtt-worker-dev
      username: 
      password: 
    topics:
      temperature: coffeeMachine/+/temperature
      water-level: coffeeMachine/+/waterLevel
      milk-level: coffeeMachine/+/milkLevel
      beans-level: coffeeMachine/+/beansLevel
      status: coffeeMachine/+/status
      usage: coffeeMachine/+/usage

backend:
  api:
    base-url: http://localhost:8080
    endpoints:
      machine-status: /api/machine/{id}/status
      machine-levels: /api/machine/{id}/levels
      machine-history: /api/machine/{id}/history
      machine-alerts: /api/machine/{id}/alerts

# Sensor Data Simulator Configuration
simulator:
  enabled: true  # Enable/disable the simulator
  interval-ms: 30000  # Data generation interval in milliseconds (30 seconds)
  machines: 5  # Number of simulated coffee machines
  
  # Decrease rates per interval (percentage points)
  decrease-rates:
    water: 1.0    # Water level decreases by 1% per interval when ON
    milk: 0.5     # Milk level decreases by 0.5% per interval when ON  
    beans: 0.3    # Beans level decreases by 0.3% per interval when ON
  
  # Temperature variation settings
  temperature:
    variation: 2.0  # Temperature variation range in Celsius
  
  # Usage event generation
  usage:
    probability: 0.3  # 30% chance of generating usage event per interval

logging:
  level:
    com.example.coffeemachine: DEBUG
    org.springframework.integration: DEBUG
    org.eclipse.paho: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: prod
  mqtt:
    broker:
      url: ${MQTT_BROKER_URL:tcp://localhost:1883}
      client-id: coffee-machine-mqtt-worker-prod
      username: ${MQTT_USERNAME:}
      password: ${MQTT_PASSWORD:}
    topics:
      temperature: coffeeMachine/+/temperature
      water-level: coffeeMachine/+/waterLevel
      milk-level: coffeeMachine/+/milkLevel
      beans-level: coffeeMachine/+/beansLevel
      status: coffeeMachine/+/status
      usage: coffeeMachine/+/usage

backend:
  api:
    base-url: ${BACKEND_API_URL:http://localhost:8080}
    endpoints:
      machine-status: /api/machine/{id}/status
      machine-levels: /api/machine/{id}/levels
      machine-history: /api/machine/{id}/history
      machine-alerts: /api/machine/{id}/alerts

logging:
  level:
    com.example.coffeemachine: INFO
    org.springframework.integration: INFO
    org.eclipse.paho: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"