spring:
  application:
    name: coffeemachine

  datasource:
    url: jdbc:h2:mem:coffeemachine;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.springframework: INFO

mqtt:
  broker-url: tcp://localhost:1883
  client-id: coffeemachine-app-dev
  username: ''
  password: ''
  topics:
    base: coffeeMachine
    commands: coffeeMachine/commands

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/coffeemachine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:coffeemachine}
    password: ${DB_PASSWORD:coffeemachine}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: true

mqtt:
  broker-url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  client-id: ${MQTT_CLIENT_ID:coffeemachine-app}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  topics:
    base: coffeeMachine
    commands: coffeeMachine/commands

server:
  port: 8080