# Coffee Machine Monitoring Application Configuration
spring:
  application:
    name: coffee-machine-monitoring
  
  # Profile Configuration
  profiles:
    active: dev
  
  # JPA Configuration (common across profiles)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
    open-in-view: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Application-specific Configuration
app:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:defaultDevSecretKey123456789012345678901234567890} # Override in production
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  
  # Alert Configuration
  alerts:
    debounce-interval-ms: 300000 # 5 minutes
    thresholds:
      water-level: 20
      milk-level: 20
      beans-level: 20
  
  # Dashboard Refresh Intervals
  dashboard:
    facility-refresh-ms: 30000 # 30 seconds
    admin-refresh-ms: 60000 # 60 seconds

# Logging Configuration
logging:
  level:
    com.example.coffeemachine: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# DEVELOPMENT PROFILE
spring:
  config:
    activate:
      on-profile: dev
  
  # H2 Database for Development
  datasource:
    url: jdbc:h2:mem:coffeedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  
  flyway:
    enabled: false
  
  # Development SQL initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql

# MQTT Configuration for Development (Local Mosquitto)
mqtt:
  broker:
    url: tcp://localhost:1883
    client-id: coffee-machine-dev
    username: 
    password: 
    clean-session: true
    connection-timeout: 30
    keep-alive-interval: 60
    max-inflight: 10
  topics:
    temperature: coffeeMachine/+/temperature
    water-level: coffeeMachine/+/waterLevel
    milk-level: coffeeMachine/+/milkLevel
    beans-level: coffeeMachine/+/beansLevel
    status: coffeeMachine/+/status
    usage: coffeeMachine/+/usage
    commands: coffeeMachine/+/commands

# Development Logging
logging:
  level:
    com.example.coffeemachine: DEBUG
    org.springframework.integration.mqtt: DEBUG
    org.hibernate.SQL: DEBUG

---
# PRODUCTION PROFILE
spring:
  config:
    activate:
      on-profile: prod
  
  # MySQL Database for Production
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_machine_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:coffee_user}
    password: ${DB_PASSWORD:coffee_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# HiveMQ Cloud Configuration for Production
mqtt:
  broker:
    url: ${MQTT_BROKER_URL:ssl://your-cluster.s1.eu.hivemq.cloud:8883}
    client-id: ${MQTT_CLIENT_ID:coffee-machine-prod}
    username: ${MQTT_USERNAME:your-username}
    password: ${MQTT_PASSWORD:your-password}
    clean-session: false
    connection-timeout: 30
    keep-alive-interval: 60
    max-inflight: 10
    ssl:
      enabled: true
      trust-store: ${MQTT_TRUST_STORE:}
      trust-store-password: ${MQTT_TRUST_STORE_PASSWORD:}
  topics:
    temperature: coffeeMachine/+/temperature
    water-level: coffeeMachine/+/waterLevel
    milk-level: coffeeMachine/+/milkLevel
    beans-level: coffeeMachine/+/beansLevel
    status: coffeeMachine/+/status
    usage: coffeeMachine/+/usage
    commands: coffeeMachine/+/commands

# Production Security
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

# Production Logging
logging:
  level:
    com.example.coffeemachine: INFO
    org.springframework.integration.mqtt: WARN
  file:
    name: /var/log/coffee-machine/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

---
# TEST PROFILE
spring:
  config:
    activate:
      on-profile: test
  
  # H2 Database for Testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  flyway:
    enabled: false

# MQTT Configuration for Testing (Testcontainers)
mqtt:
  broker:
    url: tcp://localhost:1883
    client-id: coffee-machine-test
    username: 
    password: 
    clean-session: true
    connection-timeout: 10
    keep-alive-interval: 30
    max-inflight: 5
  topics:
    temperature: coffeeMachine/+/temperature
    water-level: coffeeMachine/+/waterLevel
    milk-level: coffeeMachine/+/milkLevel
    beans-level: coffeeMachine/+/beansLevel
    status: coffeeMachine/+/status
    usage: coffeeMachine/+/usage
    commands: coffeeMachine/+/commands

# Test Configuration
app:
  jwt:
    secret: "testSecretKey123456789012345678901234567890"
    expiration-ms: 3600000 # 1 hour for tests
  alerts:
    debounce-interval-ms: 1000 # 1 second for faster tests

# Test Logging
logging:
  level:
    com.example.coffeemachine: DEBUG
    org.springframework.test: WARN
    org.testcontainers: WARN